#!/usr/bin/env bash

case "$1" in
  --menu)
    wofi & disown;;
  --terminal)
    alacritty & disown;;
  --ss-full)
    grimshot --notify save output \
      ~/Pictures/screenshot/$(date "+%Y%m%d-%H%M%S")_grim_full.png & disown;;
  --ss-area)
    grimshot --notify save area \
      ~/Pictures/screenshot/$(date "+%Y%m%d-%H%M%S")_grim_area.png & disown;;
  --ss-win)
    grimshot --notify save window \
      ~/Pictures/screenshot/$(date "+%Y%m%d-%H%M%S")_grim_win.png & disown;;
  *)
    echo "invalid option: \"$1\"";;
esac
