require('tuka.plugins-setup')
require('tuka.core.options')
require('tuka.core.keymaps')
require('tuka.core.colorscheme')

-- plugins
require('tuka.plugins.telescope')
require('tuka.plugins.lualine')
require('tuka.plugins.treesitter')
require('tuka.plugins.bufferline')
require('tuka.plugins.git')
require('tuka.plugins.gitsigns')
require('tuka.plugins.git-conflict')
require('tuka.plugins.mason')
require('tuka.plugins.lsp.lspconfig')
require('tuka.plugins.lsp.lspsaga')
require('tuka.plugins.lsp.lspkind')
require('tuka.plugins.lsp.null-ls')
require('tuka.plugins.cmp')
require('tuka.plugins.luasnip')
require('tuka.plugins.toggleterm')
require('tuka.plugins.colorizer')
require('tuka.plugins.comment')
require('tuka.plugins.autopairs')
require('tuka.plugins.ts-autotag')
require('tuka.plugins.scrollbar')
require('tuka.plugins.web-devicons')
