#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# If there are multiple displays, configure for each display.
# Check the display name with the xrandr command.
bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Google-chrome desktop='^2'
bspc rule -a Screenkey manage=off

#### BSPWM coloring ####
bspc config normal_border_color           "#4c566a"
bspc config active_border_color           "#1e1e1e"
bspc config focused_border_color          "#5e81ac"
bspc config presel_feedback_color         "#5e81ac"

#### Launch the program ####
/home/tuka/.config/polybar/launch.sh

pgrep -x picom > /dev/null || picom -b
pgrep -x fcitx > /dev/null || fcitx &

/usr/bin/feh --randomize --bg-fill /home/tuka/Pictures/wallpapers > /dev/null 2>&1
