#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x fcitx > /dev/null || fcitx &

# If there are multiple displays, configure for each display.
# Check the display name with the xrandr command.
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#### BSPWM coloring ####
bspc config normal_border_color           "#4c566a"
bspc config active_border_color           "#1e1e1e"
bspc config focused_border_color          "#5e81ac"
bspc config presel_feedback_color         "#5e81ac"

#### polybar ####
/home/tuka/.config/polybar/launch.sh

